image: Visual Studio 2022

configuration:
  - Release

before_build:
  - dotnet restore
  - choco install opencover.portable
  - choco install codecov

# Testing for English locale
test_script:
  - OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test -filter:"+[InfiniteDecimal]* -[*.Test]* -[*.CodeGenerator]* -[*.Benchmark]*" -output:".\InfiniteDecimal_coverage.xml" -oldstyle
  - codecov -f "InfiniteDecimal_coverage.xml"

  # Testing for Russian locale
  - powershell -Command "Set-Culture ru-RU"
  - dotnet test --configuration Release
