name: CI

on:
  push:
    branches:
      - '**'  # tests only branches, ignoring tags
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        locale: [en_US.UTF-8, ru_RU.UTF-8]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install locales
        run: |
          sudo locale-gen en_US.UTF-8 ru_RU.UTF-8
          sudo update-locale

      - name: Set locale to ${{ matrix.locale }}
        run: |
          export LC_ALL=${{ matrix.locale }}
          export LANG=${{ matrix.locale }}
          locale

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Test with locale ${{ matrix.locale }}
        env:
          LANG: ${{ matrix.locale }}
          LC_ALL: ${{ matrix.locale }}
        run: dotnet test --configuration Release --collect:"XPlat Code Coverage" --results-directory:./.testResults

      - name: Debug Test Results  2
        run: |
          FILE=$(find ./.testResults -name "coverage.cobertura.xml" | head -n 1)
          cp "$FILE" ./InfiniteDecimal_coverage.xml

      - name: Upload Coverage to CodeCov
        uses: codecov/codecov-action@v3
        with:
          files: ./InfiniteDecimal_coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          verbose: true
          fail_ci_if_error: true
